### ISSUE TITLE
SproutFormsGoogleRecaptchaCheckbox is not defined in sproutFormsRecaptchaOnloadCallback

### ISSUE THREAD

**Issue by paweltatarczuk** [barrelstrength/craft-sprout-forms-google-recaptcha#30] opened 2020-09-30 12:28 UTC
### Description (screenshots, logs, ...)

Sentry is reporting a lot errors like this:

- Can't find variable: SproutFormsGoogleRecaptchaCheckbox
- ReferenceError: SproutFormsGoogleRecaptchaCheckbox is not defined

### Steps to reproduce

This is tricky as I'm not able to reproduce this issue.

### Additional info

- Craft version: 3.5.5
- PHP version: 7.2
- Database driver & version:  MySQL 8
- Plugins & versions: barrelstrength/sprout-forms-google-recaptcha:1.4.0

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

The DOM structure is like so:

```
<body>
  <script src="***/cpresources/dc412562/recaptcha_v2_checkbox.js?v=1594653312" defer></script>
  <script>if (typeof sproutFormsRecaptchaOnloadCallback === 'undefined') {
    var sproutFormsRecaptchaOnloadCallback = function() {
    new SproutFormsGoogleRecaptchaCheckbox({
    siteKey: '***',
    theme: 'light',
    size: 'normal',
    customValidityText: "Please fill out this field.",
    grecaptcha: grecaptcha
    });
    };
    };</script>

  ...

   <script src="https://www.google.com/recaptcha/api.js?onload=sproutFormsRecaptchaOnloadCallback&amp;render=explicit&amp;hl=en" async defer></script>
</body>
```

**Comment by paweltatarczuk** [comment] 2020-09-30 12:33
I suppose this happens because of the `async` attribute for the `recaptcha/api.js` script, the onload may get executed before the `recaptcha_v2_checkbox.js` since it is deferred until the DOM is parsed.

**Comment by brianjhanson** [comment] 2022-07-28 13:49
I'm also having this issue which is resulting in the captcha showing up sporadically. For me, it looks like when the script is loaded via memory cache, the captcha breaks, but if it's loaded via the network or even disk cache it works as expected. I'm not intimately familiar with how the browser cache works, but I'd expect the memory cache is relatively short lived, so you'd hit this error more frequently when filling loading forms in a relatively short amount of time.

**Comment by BenParizek** [comment] 2023-01-17 06:31
Sprout Forms v3.13.12 fixes a bug where async form submissions were not properly wrapped in the promise chain which could have caused issues like this while processing Google ReCaptcha.

While I haven't been able to reproduce to confirm this is the same issue, as this is an older bug, I'm closing it out. If anybody runs into this again, please re-open with new comments.

**Closed as completed by BenParizek** 2023-01-17 06:31 UTC
Labels: bug, c3
